# This is a basic workflow to help you get started with Actions

name: auto_update

# Controls when the action will run. 
on:
  # auto update
  schedule:
  - cron: "0 10 * * *" # Runs at 10:00 UTC every day. 


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: ./assets/python

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run update on data
        run: python update_data.py

      - name: Add & Commit
        uses: EndBug/add-and-commit@v7.2.0
        with:
           author_name: UpdateBot
           message: "Updated rki dataset"
           add: 'assets/data/*'
